### ISSUE TITLE
Dynamic filtering not working?

### ISSUE THREAD

**Issue by thunderstorm654** [khoait/DCE.PCF#117]
**Component**

PolyLookup from DCE PCFComponents v. 1.0.6.0

**Describe the bug**

I can't seem to be able to get dynamic filtering to work. I've created a view and added a filter, referencing a text field within the form using the correct logical name of the field and enclosed within {{ }}. However it just bugs out and in the console I am seeing a parse error (client name redacted):
![image](https://github.com/khoait/DCE.PCF/assets/16837607/142a0ca6-f13b-4c83-b465-a2b261ee8ef5)

Could you confirm the syntax? I've browsed the guidance to no tomorrow, I cannot see anything wrong with my filter.
![image](https://github.com/khoait/DCE.PCF/assets/16837607/07713165-9902-4683-8ab3-6fdc0ed68bde)

This view works if I replace the tokens with a hardcoded name of a business unit and brings back the desired results.

I was trying to reference a lookup column which didn't work either, so tried to use a simple text column as above to check whether the dynamic filtering would work at all but always get this syntax error. I'm not sure why it's showing [ ] brackets in the parse error as I have not put these into the view filter. It doesn't seem to be converting the input into the field value, what am I missing? This control looks good, so hoping this is a simple mistake I'm making...!

Thanks :)

**Comment by khoait** [comment]
@thunderstorm654 thanks for reporting!

i did some research on this. apparently, in `LIKE` SQL query, the underscore `_` is a supported wildcard, so it is escaped automatically in the FetchXML and become `[_]`

I'll work on this and let you know when it's ready.

Thanks!

**Comment by thunderstorm654** [comment]
Amazing news, thank you for picking this up so swiftly! That will help me out a lot, your control is great.
Looking forward to the update 🙂

**Comment by khoait** [comment]
@thunderstorm654 this is fixed and will be included in release 1.0.0.7. cheers!

**Comment by thunderstorm654** [comment]
> @thunderstorm654 this is fixed and will be included in release 1.0.0.7. cheers!

That's great thank you @khoait! Any idea when release 1.0.0.7 will be out? We're starting a new project next week so if it's coming in the next couple of weeks we'll wait for the next release :)

**Comment by khoait** [comment]
@thunderstorm654 happy to share that Release 1.0.0.7 is available now https://github.com/khoait/DCE.PCF/releases/tag/v1.0.7.0
