### ISSUE TITLE
solution is blocked from being imported into managed environment

### ISSUE THREAD

**Issue by lennardtabuno** [khoait/DCE.PCF#127]
When importing the solution to an Enabled Managed Environment set to Block, multiple critical, high, and medium issues are thrown back. SARIF file is attached. What can be done to mitigate this?
[20240802010950_dcepcfcomponents.zip](https://github.com/user-attachments/files/16465598/20240802010950_dcepcfcomponents.zip)
![Screenshot 2024-08-02 125657](https://github.com/user-attachments/assets/48c8d2ad-d484-45ed-bd12-0bb73f5e754e)

**Comment by khoait** [comment]
thanks for reporting! not sure why the build command didn't use the Release configuration. I've rebuilt and updated the solution file in the Release, you can see the file size is much smaller now (270KB, was 330KB). please download and try again. cheers!

**Comment by khoait** [comment]
closing it for now. feel free to reopen or open a new one if needed. thanks!
