### ISSUE TITLE
Problem with wrapping of labels/strings for small displays/large scaling

### ISSUE THREAD

**Issue by wenstarner** [khoait/DCE.PCF#132]
**Component**
Lookdown v1.2.0.0

**Describe the bug**
When using larger scaling, or on smaller displays (or laptop screens), long strings don't wrap well.

**Steps to Reproduce**
This can be reproduced by using medium-length strings for either options or group labels, and testing on a small screen or a screen with large scaling.

**Expected behavior**
Wrapping of long strings, and 'pushing down' content so that the wrapping can fit. Like how the OOB dropdown menus work. Note the light grey highlighting for option currently hovered over, showing the increased space for the option with a wrapped label
![image](https://github.com/user-attachments/assets/3e012914-1948-427a-8ac6-452534939d7e)

**Actual behavior**
I think that the text is wrapping, and the original vertical locations are fixed to assume single-line items? Perhaps a picture is worth a thousand words:
<img width="242" alt="image" src="https://github.com/user-attachments/assets/3a53ac9b-ebc6-4d54-a6ce-c1a13038a257">

**Comment by khoait** [comment]
@wenstarner thanks for reporting! I'll add it to the backlog.
