### ISSUE TITLE
Failed To Load

### ISSUE THREAD

**Issue by clehnerhv** [khoait/DCE.PCF#149]
**Component**

PolyVlook v1.5.0

**Describe the bug**

"Failed to load data"

I have created a many to many relationship
And Set the configs
But it fails to load

Are there more screen shots of the basic configs to be able to search a related table and select multiple values
I don't need filtering or anything like that.

Thanks,

Christian

**Steps to Reproduce**

**Expected behavior**

**Actual behavior**

A clear and concise description of what you experienced.

**Screenshots**

**Additional context**

Add any other context about the problem here. Eg., solution version, Power Platform environment, ...

**Comment by khoait** [comment]
Hi @clehnerhv, thanks for reporting! Can you share the relationship screenshot, and how you setup the component properties?

**Comment by clehnerhv** [comment]
Thanks for the quick reply!

It is blocking me from uploading but i can write it out

Many to Many
Current       Related
Requests     Confirmation Recipients
Relationship table name
Requests_cr1ae_ConfirmationRecipients_cr1ae_ConfirmationRecipients




Component Properties:

Table Column
Confirmation Recipient List

Relationship Type
nton

Relationship Name
Bind to table column
No
Static Value
Requests_cr1ae_ConfirmationRecipients_cr1ae_ConfirmationRecipients

Relationship 2 Name
Bind to table column
No
Static Value
blank

Should Ouput Selected Text
Value
True
Output Selected Field
Table Column
Select an option
Lookup View
Confirmation Recipients Lookup View

Item Limit
Static Limit
20
Allow Quick Create
Value
false
Tag Action
Value
none
Language Pack Path
Bind to table column
No
Static Value
Empty

**Comment by khoait** [comment]
@clehnerhv thanks for your info. Looks like you are using relationship table name instead of relationship logical name.

Please make sure to use relationship table name, see my samples here

https://github.com/khoait/DCE.PCF/wiki/PolyLookup#sample-relationship-names

Hope it helps!

**Comment by clehnerhv** [comment]
I am grabbing the one in the red box, which I think is the logical name. Is there anything else you think it could be?

**Comment by khoait** [comment]
Can you check again? the prefix in `Requests_cr1ae_ConfirmationRecipients_cr1ae_ConfirmationRecipients` doesn't look correct.
It'll be better to see if you can share some screenshots.

**Comment by clehnerhv** [comment]
Hi thank you! I deleted the reltationship created a new one and referenced it and it is now working!
Is there a way to return specific columns? 
Is that with a fetch?

Thanks!

Christian

**Comment by khoait** [comment]
Glad that it's working. Yes there are flexible ways to provide custom lookup view, please see more details here

https://github.com/khoait/DCE.PCF/wiki/PolyLookup#lookup-view

**Comment by khoait** [comment]
Closing this as it is resolved! feel free to open a new issue if needed. thanks!
