### ISSUE TITLE
Dropdown for values sometimes sits off the page [screenshots included]

### ISSUE THREAD

**Issue by wenstarner** [khoait/DCE.PCF#160]
**Component**

PolyLookup

**Describe the bug**

When clicking to open the dropdown list of values, sometimes the list sits off the page. Screenshots show this behaviour.

**Steps to Reproduce**

**Example 1:**
Monitor is 4k, browser zoom is 100%
Clicking to see the dropdown list of values will show the dropdown list partly off the page. It's hard to see in this screenshot, but the left side of the dropdown is cut off:
<img width="1707" alt="image" src="https://github.com/user-attachments/assets/ff37b0c2-564e-488f-ab8a-02cec40c5223">

**Example 2:**
Monitor is 4k, browser zoom is 110%
Clicking to see the dropdown list will show the dropdown list like this. Note how it is partly cut off at the top of the page:
<img width="904" alt="image" src="https://github.com/user-attachments/assets/03df14cd-e538-4e05-9d0d-85f76f15239c">

**Expected behavior**

Dropdown lists should not be cut off. Perhaps scaled to a percentage of the browser window?

**Actual behavior**

Dropdown list was cut off, at 100% zoom in one way (left half cut off), and then at 110% zoom in another way (top cut off).

**Screenshots**

Provided above.

**Comment by wenstarner** [comment]
Sorry to bother you again @khoait , but I thought you might like to know about this one

**Comment by khoait** [comment]
@wenstarner this is fixed and will be included in the next minor release
