### ISSUE TITLE
Lookdown Dynamic Filtering Bug

### ISSUE THREAD

**Issue by satriotsubasa** [khoait/DCE.PCF#161]
**Component**

Lookdown

**Describe the bug**

Hi @khoait , after some troubleshooting, I think I found the root cause.

I'm using this XML schema for the dynamic filtering for my "City" lookup field which has dependencies with "Country" lookup field:
I tried to bind this filter in a description text field, when I'm using this XML, is not working,:
![image](https://github.com/user-attachments/assets/26326e59-65de-4553-bb84-dd345a3896dc)

But when I manually updated the country.id like below, it's working and the filtering on the "City" lookup is updated:
![image](https://github.com/user-attachments/assets/32ad92fb-2eeb-492f-8a14-141cf800340c)

I suspect that the "{{ new_country.id }}" is not being updated when we changed the dependent field (in my case is "Country").
I hope that helps and thanks a lot once again.

**Steps to Reproduce**

1. Create Transaction, Country and City table
2. In Transaction table, create a Lookup field to the Country table
3. In Transaction table, create a Lookup field to the City Table (with a lookup field to the country table on the City table)
4. Add Lookup Country and Lookup City fields to Transaction form, set the dynamics filtering as above screenshot

**Expected behavior**

The City lookup field should be filtered based on the Country lookup field

**Actual behavior**

The City lookup field is not being filtered based on the Country lookup field, after troubleshooting I found a possible root cause (describe above)

**Comment by khoait** [comment]
@satriotsubasa this is fixed in the latest release! thanks for your contribution!

**Comment by satriotsubasa** [comment]
Hi @khoait , it's working perfectly now, I'm the one who should be saying thanks!
