### ISSUE TITLE
Polylookup Display not updating for create mode form

### ISSUE THREAD

**Issue by satriotsubasa** [khoait/DCE.PCF#162]
**Component**

Polylookup

**Describe the bug**

Hi @khoait , I found another bug after the new look being introduced for Polylookup. The polylookup display doesn't updated with the selected value, instead it only show "loading", (please kindly see screenshot below). Seems like there is no problem with the display for custom relationship type.

**Steps to Reproduce**

1. Create nton relationship OR custom relationship type in polylookup
2. Add that polylookup field into the form
3. Create a new record (form in create mode)
4. Select one or more value in the polylookup

**Expected behavior**

The selected value is visible on the polylookup

**Actual behavior**

The polylookup only show "loading"

**Screenshots**

![image](https://github.com/user-attachments/assets/bcecca27-3314-4c9b-8650-8071ad742666)

**Comment by satriotsubasa** [comment]
Hi @khoait , I updated the context of this issue, now this issue is happened for all type of relationship when we're in the create form.

**Comment by khoait** [comment]
Thanks @satriotsubasa! I'll look into it this evening.

**Comment by khoait** [comment]
@satriotsubasa this is fixed and will be included in the next minor release

**Comment by satriotsubasa** [comment]
awesome! many thanks @khoait
