### ISSUE TITLE
Type search when the nothing selected from dropdown.

### ISSUE THREAD

**Issue by shaharyar-z-ali** [khoait/DCE.PCF#166]
**Component**
PolyLookup

**Describe the bug**
The search feature (typing in the bar) doesn't work unless one option is selected from the dropdown.

When I'm searching for a lookup field by typing, it won't let me type unless I select one option from the drop-down first.

**Expected behavior**

Start the search by typing even if an option is not selected

Something like this:
![image](https://github.com/user-attachments/assets/51163416-e75d-4259-ad2f-44ef7fb41e99)

**Actual behavior**

Select 1 option first from the dropdown and then allows you to search by typing

**Screenshots**
Can't type and search by clicking on the bar:
![image](https://github.com/user-attachments/assets/46545c39-8af5-43f0-af00-c950abeb1c76)

Once I select an option then it allows me to type:
![image](https://github.com/user-attachments/assets/3a271059-178b-474e-a5b1-ac0760982927)

**Comment by khoait** [comment]
@shaharyar-z-ali thanks for reporting. I'll check this.

**Comment by khoait** [comment]
@shaharyar-z-ali which version are you using? it's working fine for me with polylookup v1.6.1 in latest release 1.1.0.1. could you check again?

**Comment by shaharyar-z-ali** [comment]
Hi, thanks for the response. I’m using the one before this one. 1.6.0

**Comment by shaharyar-z-ali** [comment]
I updated to the new one and it's working perfect. Thank you so much. Good to close this issue.
