### ISSUE TITLE
Polylookup getting cleared when OnSave during Create Form

### ISSUE THREAD

**Issue by satriotsubasa** [khoait/DCE.PCF#167]
**Component**

Polylookup

**Bug Description and how to reproduce**

Hi @khoait , I found this bug when I'm on the Create Form mode, after selecting values on the lookup field then click 'Save' on the form, the values that has been selected on the polylookup field being cleared right after.

Kindly see below screenshot, based on audit history, after "create" the value being deleted (I don't have any JavaScript or Plugin):
![image](https://github.com/user-attachments/assets/5b726568-82d5-4e2e-97f3-7c5a829c284c)

This bug is not happening on the Edit Form.

**Expected behavior**

The value that has been selected during Create mode form will be saved and not being cleared.

**Actual behavior**

after selecting values on the lookup field then click 'Save' on the form, the values that has been selected on the polylookup field being cleared right after.

**Comment by khoait** [comment]
Hi @satriotsubasa, it's a known limitation for now. Out of the box, we'll need to save the main/parent record first before we can add any related/children records. To workaround this, we'll need to save the json to a field, and we'll need to write some logic (could be a flow or a plugin) to read the json and create related records after the main record is created.

Please read more about this here: https://github.com/khoait/DCE.PCF/wiki/PolyLookup#selected-items. I also have a sample plugin for this scenario.

Hope it helps!

**Comment by satriotsubasa** [comment]
Hi @khoait , I see, I've also built the plugin to handle the JSON code, thanks for the clarification.

**Comment by satriotsubasa** [comment]
Hi @khoait , I see, I've also built the plugin to handle the JSON code, thanks for the clarification.
