### ISSUE TITLE
Option to always show expanded info on PolyLookup results

### ISSUE THREAD

**Issue by jeremystokese2** [khoait/DCE.PCF#168]
**Describe Problem**

We're using PolyLookup to enable a multi-select experience across an N:N relationship, using a Lookup View to filter possible options by a common parent record.

We would like more contextual information about the record to always be present without needing to manually expand a row to see additional fields from the Lookup View

As a stop-gap, we are using PowerFx calculated columns to merge additional information into a single field
![image](https://github.com/user-attachments/assets/2b3cc944-1a32-43cc-8514-1a08fc91c487)

**Suggest Solution/Expectation**

An option on the component config to always show additional fields (i.e. records are always 'expanded') on PolyLookup results

**Comment by khoait** [comment]
thanks for your idea! I'll put this in the backlog to work on.

**Comment by khoait** [comment]
@jeremystokese2 this is now available in the latest release v1.1.1.0: https://github.com/khoait/DCE.PCF/releases/tag/v1.1.1.0
please checkout the new `Show Option Details` property
