### ISSUE TITLE
Cannot build component because of handlebars

### ISSUE THREAD

**Issue by headsetsniper** [khoait/DCE.PCF#17]
**Describe the bug**
When trying to build the project, I get the following Error:
require.extensions is not supported by webpack. Use a loader instead.
 @ ./PolyLookup/components/PolyLookupControl.tsx 173:35-56
 @ ./PolyLookup/index.ts 154:39-80

WARNING in ./node_modules/handlebars/lib/index.js 22:2-20
require.extensions is not supported by webpack. Use a loader instead.
 @ ./PolyLookup/components/PolyLookupControl.tsx 173:35-56
 @ ./PolyLookup/index.ts 154:39-80

ERROR in ./node_modules/handlebars/lib/index.js 15:11-24
Module not found: Error: Can't resolve 'fs' in 'C:\Sources\CustomerProjects\DCE.PCF\PolyLookupComponent\node_modules\handlebars\lib'
resolve 'fs' in 'C:\Sources\CustomerProjects\DCE.PCF\PolyLookupComponent\node_modules\handlebars\lib'
  Parsed request is a module
  using description file: C:\Sources\CustomerProjects\DCE.PCF\PolyLookupComponent\node_modules\handlebars\package.json (relative path: ./lib)
    resolve as module
      C:\Sources\CustomerProjects\DCE.PCF\PolyLookupComponent\node_modules\handlebars\lib\node_modules doesn't exist or is not a directory

**Steps to Reproduce**
1. Clone The Repostory
2. npm install
3. npm run build

Since there is a //TODO: fix this hack at the line that causes this build error (Line 21 PolyLookupControl.tsx, I assume you are already aware of this problem and your fix apparentyl doesnt work everywhere. Any Idea how I can make it work? I am on Windows, vscode, fresh clone.
node --version = v16.17.0

**Comment by khoait** [comment]
yeah, I got this one as well. I leave a TODO comment in code to fix this. 

For now, you can workaround this by editing the `browser` setting in 

`node_modules/handlebars/packgage.json` line 79:
```
"browser": "./dist/cjs/handlebars.js",
```

I'm not sure how to fix this at the moment, tbh. I can see there are people with similar issues in handlebars repo. I'll keep an eye on them.

**Comment by khoait** [comment]
@headsetsniper this should be fixed in `main` now. Please try again from your side.
