### ISSUE TITLE
Preview any column instead of primary name column in the bar 

### ISSUE THREAD

**Issue by shaharyar-z-ali** [khoait/DCE.PCF#170]
I have a primary name column (ID) shown when selected from the dropdown.

![image](https://github.com/user-attachments/assets/c8958fae-cbe5-4a9e-a096-5226893da8be)

Is it possible that instead of the ID (primary name column), it gives the option to show any column that is associated with that ID?

**Comment by khoait** [comment]
thanks for your idea! it's could be a new feature where you can provide a template of what to show in the selected item text. I'll put this in the backlog.

**Comment by shaharyar-z-ali** [comment]
Great thank you so much.

**Comment by shaharyar-z-ali** [comment]
Just to confirm, template as in the column schema name or the data type?

**Comment by khoait** [comment]
a simple text property with liquid template should do. similar to what we have Lookdown component.
For example, we can have a template like this `{{ new_fullname }} ({{ new_email }})` and the selected item text should show `John Doe (jdoe@test.com)`

**Comment by shaharyar-z-ali** [comment]
That would be amazing, thanks

**Comment by khoait** [comment]
@shaharyar-z-ali this is completed and will be included in the next release. cheers!

**Comment by khoait** [comment]
@shaharyar-z-ali this is now available in the latest release v1.1.1.0 https://github.com/khoait/DCE.PCF/releases/tag/v1.1.1.0
please see wiki for templating syntax: https://github.com/khoait/DCE.PCF/wiki/PolyLookup#selected-item-text

**Comment by shaharyar-z-ali** [comment]
Hi, 

First of all, thank you so much for updating these.

This works amazing. Just a quick thing, if I'm missing something, It used to show more records but now it's not showing. Do I have to change anything for this?

![image](https://github.com/user-attachments/assets/e4df86a6-124e-451d-a6da-88be359142e9)
