### ISSUE TITLE
PolyLookup: A few observations

### ISSUE THREAD

**Issue by wenstarner** [khoait/DCE.PCF#171]
**Component**

PolyLookup v 1.1.0.1

**Describe the bug**

1. Text size appears small on a 4K monitor at native resolution, at 100% browser zoom. I was wondering if it is possible to match the text size for the tag with the text size for the field label? This is how it seems to work with the native lookup control. The first screenshot below is how it looks on my screen. The second screenshot is a native control—for this control, when I zoom in and out, the tag text size always appear to match the label text size.

2. Icons do not appear to be rendered as transparent. The third screenshot below is what I see. These icons are SVG and I have seen them elsewhere as transparent (e.g., when appearing in the navigation pane on the left side of the app).

3. When I type some text and select the corresponding filtered lookup option, it would be nice if the text that I've typed could be deleted, due to the relevant lookup now being selected. The first screenshot below shows what I mean—I typed 'germany' and selected the option, but now I have to manually delete the text that I typed.

4. I'm not sure how, but is there a way to indicate that the lookup list only shows 'some' options? See the fourth screenshot below. The lookup list doesn't go past 'D'. For a countries list this is kind of obvious, but it might confuse users who believe the lookup list is incomplete. Alternatively, for bespoke lookup lists, users might not know that there are further options in the list.

Alternatively, the native lookup seems to populate the lookup list with more records when the user scrolls to the bottom of the list. Could this be an option?

![image](https://github.com/user-attachments/assets/852bd7cc-c514-4f49-98c3-4cafc1fb3d6b)

![image](https://github.com/user-attachments/assets/a1d72ea1-17d9-4a8f-b736-bd1166cd31e8)

![image](https://github.com/user-attachments/assets/b862965d-be35-46e2-95d6-188c3440ee22)

![image](https://github.com/user-attachments/assets/064638cd-b726-4cfc-ab61-8d0f68e3b6a9)

**Comment by SoldierFace** [comment]
I think this will help you.
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by odoyhaha** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by wenstarner** [comment]
1. Looks like the two posts above are bots...
2. Sorry for posting this as a bug. This is more to do with feature requests! I don't know how to change the Category though

**Comment by khoait** [comment]
@wenstarner thanks for your ideas! they're all valid points. I'll put this in the backlog for the next release.

**Comment by khoait** [comment]
@wenstarner this is completed and will be available in the next release. thanks!

**Comment by khoait** [comment]
@wenstarner this is now available in the latest release v1.1.1.0 https://github.com/khoait/DCE.PCF/releases/tag/v1.1.1.0
please have a look. cheers!
