### ISSUE TITLE
Picking the search string as ID (primary name column) in Quick Create

### ISSUE THREAD

**Issue by shaharyar-z-ali** [khoait/DCE.PCF#174]
**Component**

PolyLookup 1.6.1

**Describe the bug**

When searching for a text in field, it shows the option to quick create but when the record is created, it makes takes that search string as the ID (primary name column) which in my case is read-only and datatype is autonumber.

**Expected behavior**

The search field should not be used anywhere if quick create is used. (maybe used in name if that helps as that field is editable freeform.

**Actual behavior**

Being used in the primary name column as an ID (in this case)

**Screenshots**

The search:
![image](https://github.com/user-attachments/assets/dd4baab9-a9cd-4f89-9705-c8140cd3f880)

The search string used as contact ID (primary name column)
![image](https://github.com/user-attachments/assets/46142744-e578-4306-a7a0-f712fe21d99a)

**Comment by khoait** [comment]
@shaharyar-z-ali thanks for reporting! I'll work on this.

**Comment by khoait** [comment]
@shaharyar-z-ali this is fixed and will be available in the next release. cheers!

**Comment by khoait** [comment]
@shaharyar-z-ali this is now available in the latest release v1.1.1.0 https://github.com/khoait/DCE.PCF/releases/tag/v1.1.1.0
please have a look. cheers!
