### ISSUE TITLE
Filtered list does not change when Dynamic Template lookup value changed

### ISSUE THREAD

**Issue by jasonpughironbyte** [khoait/DCE.PCF#180]
**Component**

PolyLookup v1.6.1

**Describe the bug**

The filtered list is not updated when using Dynamic Templating (FetchXML) when the filtering lookup value is changed.

I have 4 tables in my solution:

Event
Category
Topic
Sub Topic

Each event has a Category, Topic and 1 to many Sub Topics.  Topics are related (and filtered) based on the Category.  Sub Topics are related (and filtered) to a Topic.

Sub Topics is using the PolyLookup control.  I am using the Lookup View to filter the list of Sub Topics based on the Topic the user has selected.  The filtering appears to be working correctly, but only after the page is manually refreshed.  This applies to selecting a Topic the first time, and also for changing the selected Topic later.  I understand that the Sub Topics can only be selected after the record is saved because it is an N:N relationship between Events and Sub Topics, however, even after saving the form, it is not until doing a refresh of the form that the Sub Topics are available in the list.

[TestNtoN_1_0_0_2.zip](https://github.com/user-attachments/files/17381494/TestNtoN_1_0_0_2.zip)

**Expected behavior**

When changing the lookup that is used in the FetchXML statement of the Lookup View, the list of items available in the list is updated.

**Actual behavior**

The picklist is not populated with anything until the form is refreshed.

**Screenshots**

![AfterInitialSave](https://github.com/user-attachments/assets/9a56e1bc-c66f-4b22-8eee-35ac12918fde)

![AfterRefresh](https://github.com/user-attachments/assets/0a909a93-0486-4501-965b-0d578ec3a65f)

**Additional context**

**Comment by khoait** [comment]
@jasonpughironbyte thanks for reporting! I tested and can see that it's working for classic look, but isn't in the new look. I'll fix this in the next release.

**Comment by jasonpughironbyte** [comment]
Awesome, thank you!

**Comment by khoait** [comment]
@jasonpughironbyte this is fixed and will be available in the next release. cheers!

**Comment by jasonpughironbyte** [comment]
@khoait Thank you!!!

**Comment by khoait** [comment]
@jasonpughironbyte this is now available in the latest release v1.1.1.0: https://github.com/khoait/DCE.PCF/releases/tag/v1.1.1.0
please have a look. cheers!
