### ISSUE TITLE
Custom N:N relationship not associating new record once quick create is saved

### ISSUE THREAD

**Issue by JesseAppEnthusiast** [khoait/DCE.PCF#183]
**Component**
PolyLookup

**Component name and version** 
PolyLookup v1.6.2

When using the custom N:N relationship with the modern experience, if there is no record found after a search, and the user opts to create a new record using the Quick Create form:

In the classic experience, after saving the Quick Create form, the new record is automatically associated with the current record. The relationship between the two entities (relationship_1 and relationship_2) is established, and the created record is displayed within the PolyLookup control.

In the modern experience, while the new record (relationship_2) is successfully created, the automatic association with the current record does not happen. The user must manually establish the relationship after creating the record.

**Steps to Reproduce**

Classic Experience
1. - Open a Student record
2. - Navigate to the Enrollment (PolyLookup) control, which is configured to show the custom N
3. - relationship between Student and Class through the Enrollment table (relationship_1: Student to Enrollment, relationship_2: Enrollment to Class).
4. - In the PolyLookup control, search for an existing Class record:
5. - If no matching Class is found in the search results, select the option to create a new Class record.
6. - The Quick Create form for the Class entity will open.
7. - Fill out the necessary fields for the new Class (e.g., Class name, description, etc.).
8. - Click Save.
9. - After saving:
10. - The system automatically creates a new Enrollment record (relationship_1) associating the current Student record with the newly created Class record (relationship_2).
11. - The newly created Class is now displayed within the PolyLookup control under the Enrollment relationship.
12. - As a result, the following happens:
13. - A new Class record is created.
14. - A new Enrollment record (relationship_1) is created, which links the current Student to the newly created Class.
15. - The PolyLookup control displays the associated Class via the Enrollment relationship.

Modern Experience
1. - Open a Student record
2. - Navigate to the Enrollment (PolyLookup) control in the same way as in the classic experience.
3. - Search for a Class record:
4. - If no matching Class is found, select the option to create a new Class record.
5. - The Quick Create form for the Class entity will open.
6. - Fill out the fields for the new Class, and click Save.
7. - After saving:
8. - The system creates the new Class record (relationship_2), but the Enrollment record (relationship_1) is not automatically created.
9. - The newly created Class is not displayed within the PolyLookup control, because the association between Student and Class through Enrollment is not established automatically.
10. - As a result, the following happens:
11. - A new Class record is created.
12. - No Enrollment record (relationship_1) is automatically created, meaning the association between the current Student and the new Class is missing.
13. - The user must manually associate or re-search for the new Class and select it in order for it to appear in the PolyLookup control.

**Expected behavior**

1. Automatically create a corresponding Enrollment record to associate the current Student record with the newly created Class record.
2. Display the newly associated Class record within the PolyLookup control under the Enrollment relationship, showing that the Student is now enrolled in the Class.

**Actual behavior**

1. When creating a new Class via the Quick Create form, the new Class record is successfully created.
2. However, the automatic creation of the Enrollment record (which associates the Student with the Class) does not occur.
3. As a result, the new Class record does not appear in the PolyLookup control, because there is no Enrollment record linking the Student to the Class.
4. The user must manually create the association between Student and Class through the Enrollment entity, which is not the expected behavior.

**Comment by khoait** [comment]
@JesseAppEnthusiast  thanks for your feedback! I'll work on this.

**Comment by khoait** [comment]
@JesseAppEnthusiast this is fixed and will be included in the next release. cheers!

**Comment by khoait** [comment]
@JesseAppEnthusiast this is now available in the latest release v1.1.1.0: https://github.com/khoait/DCE.PCF/releases/tag/v1.1.1.0
please have a look. cheers!
