### ISSUE TITLE
Make Loookdown field read only if the form mode is read only

### ISSUE THREAD

**Issue by dataverseDev** [khoait/DCE.PCF#190]
As the title reads, would be great for the Lookdown component to respect the form mode.

When the form is read only, to prevent users from being able to interact with the component completely.

**Comment by dataverseDev** [comment]
![image](https://github.com/user-attachments/assets/f425fbda-43ca-462e-b458-5244b845ba8a)

**Comment by khoait** [comment]
@dataverseDev thanks for your idea! I'll work on this for the next release.

**Comment by khoait** [comment]
@dataverseDev this is fixed and will be included in the next release. cheers!

**Comment by khoait** [comment]
@dataverseDev this is now available in the latest release v1.1.1.0: https://github.com/khoait/DCE.PCF/releases/tag/v1.1.1.0
please have a look. cheers!
