### ISSUE TITLE
[Feature]: support clearing match string after selection is added in PolyLookup

### ISSUE THREAD

**Issue by eckamm** [khoait/DCE.PCF#195]
### Problem description

After a user has searched for values and added one, the match string for the search remains in the text area.   This is undesirable in some cases as clearing the match string would be less confusing and/or a more efficient experience for the user.  In the usage pattern this feature is targeting, the user adds one selection as a result of a search and then changes the match string before adding the next item, etc.

Here is an illustration of the current behavior as of 1.6.1:

----

Step 1. 
- User types in the match string, baggins, in the text input area and gets the list of matches.
![image](https://github.com/user-attachments/assets/80ca034d-0fb5-4652-948e-f2dd90911633)

----

Step 2. 
- User clicks on a selection from the list of matches.
- The selection goes into a chiclet in the text input area.
- The match string is still displayed in the text input area.
![image](https://github.com/user-attachments/assets/f234f26d-9117-4571-a64c-a202426119c5)

The preferred behavior would be for the match string to be cleared from the text input area after an item is selected.

### Feature description

Add a new configuration option for PolyLookup:
- The configuration option could be labeled "Clear match string after selection is added".
- The default value would be false, which is the current behavior.
- Setting the value to true would indicate that the developer wants the match string to be cleared out after a user adds a selection with the control.

**Comment by khoait** [comment]
Hi @eckamm, thanks for your idea! this has been mentioned in #171 and fixed in PR #185. it will be available in the next release. cheers!

**Comment by eckamm** [comment]
That's great to hear.  Very nice component!  Thank you!

**Comment by khoait** [comment]
@eckamm this is now available in the latest release: https://github.com/khoait/DCE.PCF/releases/tag/v1.1.1.0 . please have a look. cheers!
