### ISSUE TITLE
[Feature]: improved messaging during search for PolyLookup

### ISSUE THREAD

**Issue by eckamm** [khoait/DCE.PCF#197]
### Problem description

When a search begins, "No options available" is displayed until the result appears.

If the search is slow, the user can end up thinking there are no options available when in fact there will be if they wait a few more seconds.

### Feature description

It would be nice if a different message could be shown (e.g. "Searching...") while the search is underway.

I think there *might* also be another case where the search times out but the user is left seeing "No options available", and in that case it would also be nice to show a different message (e.g. "Search timed out.").

**Comment by khoait** [comment]
@eckamm thanks for your idea! I'll include this in the next release.

**Comment by khoait** [comment]
@eckamm this is completed in the latest release v1.1.1.0: https://github.com/khoait/DCE.PCF/releases/tag/v1.1.1.0
