### ISSUE TITLE
[Feature]: Add property to choose which field we want to output from the relevant entity

### ISSUE THREAD

**Issue by JesseAppEnthusiast** [khoait/DCE.PCF#209]
### Problem description

This is for the PolyLookup
Always outputting the primary column field as comma separated list.

### Feature description

Would be great if we had a property where we could state the field logical name that we want to output, similar to the moustache template to display a field value, would be awesome if we could state the field name in moustache template and output the value from the field rather than always being the primary column.

**Comment by khoait** [comment]
@JesseAppEnthusiast thanks for your idea! this is related to #170! you can set a mustache template for the selected item text. I'll make it also output the same text.

**Comment by khoait** [comment]
@JesseAppEnthusiast this is included in the latest release v1.1.1.0! please see related wiki here: https://github.com/khoait/DCE.PCF/wiki/PolyLookup#selected-item-text
