### ISSUE TITLE
[Bug]: Text wrap doesn't work, pushing clear button out of control area

### ISSUE THREAD

**Issue by TomVineRBQ** [khoait/DCE.PCF#212]
### Component

PolyLookup

### Component version

v1.7.0

### Current Behavior

Using n:n relationship, component is pulling back the text field but isn't wrapping at all. This forces the clear button out of the way, meaning a user cannot clear their selection.

![image](https://github.com/user-attachments/assets/2d0f41cb-471a-4046-8d22-b8d6b8ac7343)

### Expected Behavior

In the default lookup component, the text is wrapped with an elipsis at the end with the clear button displaying for users to remove their selection.

![image](https://github.com/user-attachments/assets/dc7e8bf4-42a9-42d2-9a00-30d6f3d3aa00)

### Steps to reproduce

1. Create a model driven app form with 3 sections.
2. Insert blank text control of single text type
3. Insert PolyLookup PCF
4. Configure PCF to Many:Many, with relationship table name
5. Add long text string to first column in lookup view for related table

**Comment by khoait** [comment]
@TomVineRBQ thanks for reporting! I'll fix this.

**Comment by TomVineRBQ** [comment]
Thank you @khoait - please keep up the amazing work 🙏

**Comment by khoait** [comment]
@TomVineRBQ this is fixed and will be available in the next release. cheers!
