### ISSUE TITLE
Values from previous form being cached or retained when creating a new record

### ISSUE THREAD

**Issue by markgomez00** [khoait/DCE.PCF#22]
**Describe the bug**
Value is being retained when navigating to new form

**Steps to Reproduce**
1. Open existing record and populate the control using polylookup
2. Create a new record for the same table
3. Polylookup retains the values from the previous record

**Comment by khoait** [comment]
Thanks for reporting! It will be fixed in the next release.

**Comment by khoait** [comment]
Hi @markgomez00, this should be done in the [latest release v1.0.1.0](https://github.com/khoait/DCE.PCF/releases)! I'll close this for now. Please free to reopen if it still persists.
