### ISSUE TITLE
Not able to import v1.0.15

### ISSUE THREAD

**Issue by riyak33** [khoait/DCE.PCF#23]
Getting the following error while uploading the latest version file. 
![image](https://user-images.githubusercontent.com/129150593/228150607-66432b6a-2b16-40ee-b0f9-b47cf49809b7.png)

Could you please provide the managed solution file for the latest version.

**Comment by khoait** [comment]
thanks for reporting! v1.0.12 is the latest release, v1.0.15 will be released soon early April. Please check back later or Star/Watch this repo to get the notification.

**Comment by riyak33** [comment]
Thank You for the quick response! The control would be quite helpful for us since it resolves major concern of our - multiselecting users. The json output array is what we would be looking forward to. Thank you for the update!

**Comment by khoait** [comment]
Please consider giving the repo a star ⭐ if you find it helpful! Thanks 😄

**Comment by khoait** [comment]
Hi @riyak33 v1.0.16 is out with more features. Please find it in the Releases page. Thanks!
