### ISSUE TITLE
Search not working.

### ISSUE THREAD

**Issue by riyak33** [khoait/DCE.PCF#28]
I have used the latest version 1.0.16. The search feature is not working. Also, it is not fetching all the records in the lookup view. 
Also we cannot select lookup values while creating a record in table. 
Are you working on the above limitations? If yes, can you please let me know when those will be available.
![image](https://user-images.githubusercontent.com/129150593/229715099-388f5c16-1387-4f27-9018-6ddb60becc73.png)

**Comment by malkhawaja** [comment]
I have the same issue!

**Comment by malkhawaja** [comment]
thanks @khoait for your support... I can confirm that search is working fine after creating the view as you described above.

and eagerly looking forward to the fix of #29

**Comment by riyak33** [comment]
Thank You @khoait . The search is working fine after doing the said configuration. The output json array on create would indeed be quite helpful. Eagerly awaiting the fix for that. Really appreciate your response.

**Comment by khoait** [comment]
This is enhanced in PolyLookup v1.1.0 Release 1.0.2.0 now. a System View can be filtered by the Primary Attribute by default if there is no search token in the view.

**Comment by malkhawaja** [comment]
Great job... thanks 🙏
