### ISSUE TITLE
The JSON output is not generated in a create form

### ISSUE THREAD

**Issue by malkhawaja** [khoait/DCE.PCF#29]
while the documentation says that we should use the json output feature in case we need to use the pcf in a create form, and use a plugin with it, but it seems the json do not get generated unless we save the record first, I was expecting to have the json generated and saved in the record upon creation.

**Comment by khoait** [comment]
thanks for reporting! I'll work on the fix soon.

**Comment by khoait** [comment]
this should be fixed in v1.0.17 release v1.0.1.1. feel free to reopen if it still persists.
