### ISSUE TITLE
the control doesn't work in mobile player

### ISSUE THREAD

**Issue by malkhawaja** [khoait/DCE.PCF#31]
Hi,
I was testing my app on mobile and when I was trying the control, it shows the records and searches just fine, but when I click on an option to select, nothing happens!
FYI, the app is activated for an Offline profile, although the above mentioned issue while the app and device are online!

**Comment by khoait** [comment]
thanks for reporting!

Can you share what device you are using? I'm testing on my iphoneX ios 16.3.1, PowerApps v3.23033.14 and it's working fine for me even when I turn on Offline Mode.

**Comment by malkhawaja** [comment]
I'm using iPhone Xs same iOS same power apps version, and it was the same issue in Power Apps for Windows (from Windows Store)

**Comment by malkhawaja** [comment]
That's weird... I will test more thoroughly and get back to you again.

**Comment by khoait** [comment]
can you try again with v1.0.17?

**Comment by malkhawaja** [comment]
I tried the new version and now it is working fine... I suspect the issue was with a business rule defined on the field that lock it from editing while in create mode then make the field business required after creation, now the business rule is turned off and the json is generated during create mode and my plugin (created with help from chatGPT 😁) is working perfectly in online mode but with a small issue in offline mode, that when I select the record in the control then try to save, the selection disappears ... check the video 

https://user-images.githubusercontent.com/43861985/230509404-a0a7b6a3-0c37-4628-9cf0-f76320e7f6ee.MOV

**Comment by khoait** [comment]
Thanks for your effort! I'm not sure what's wrong with it as it's working fine for me (see my screen recording below). I'll try to test it on other devices later. I'll keep this open for now and revisit it in future releases.

https://user-images.githubusercontent.com/8686497/230957142-790355c9-6f61-4da6-8ea9-07930a6dab9b.mp4

**Comment by malkhawaja** [comment]
In your recording, you are editing an existing record, right? Did you try it for creating a new record?

**Comment by khoait** [comment]
ok. I tried again with my plugin in offline mode but it's not working. And I found out that because N:N relationship is not supported in Offline Mode, please see here: https://learn.microsoft.com/en-us/power-apps/mobile/offline-capabilities#limitations.

I guess there is nothing much we can do about this. I'll add this limitation to the Wiki page.
