### ISSUE TITLE
Component not working when multiple fields is configured as Polylookup

### ISSUE THREAD

**Issue by markgomez00** [khoait/DCE.PCF#34]
I have 3 text field that I have configured for polylookup but the component is not working in this case. Whenever I update one of the field the other two is populated with the same field.

Note that 3 fields is using different N:N relationships

**Comment by khoait** [comment]
Thanks for reporting! I'll fix this.

**Comment by khoait** [comment]
@markgomez00 this should be fixed in PolyLookup v1.1.1 in Release v1.0.2.1. Feel free to reopen it if it still persists.
