### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by kevinhuizer** [khoait/DCE.PCF#37]
**Describe the bug**
Configured the PCF (according to the documentation), but the control is not capable of searching. In the target lookup table I removed all special characters to see wether or not it was an encoding issue, with no luck too.

**Actual behavior**
The PCF keeps showing a list with all of the items in the table, not a filtered list based on the given query.

**Comment by kevinhuizer** [comment]
The versions is 1.0.1.0.

Lookup view filter is the default lookup view filter (leaving it blank caused it to no render, so I put it in explicitly in the configuration).

**Component configuration**
![image](https://user-images.githubusercontent.com/33622527/232563487-3d004d41-d208-4102-8410-2ca3ecdc16fb.png)

**Lookup view filter**
![image](https://user-images.githubusercontent.com/33622527/232563772-71c55070-df94-4715-98dc-df4a381dcae6.png)
![image](https://user-images.githubusercontent.com/33622527/232563853-9c37fd9d-bbc4-4507-b1fa-73d427869423.png)

**Comment by khoait** [comment]
@kevinhuizer this is fixed from PolyLookup v1.1.0 in Release v1.0.2.0. You may want to update to the latest version.

If you want to stick with the current version, you'll need to insert the search term from the component to your view using the reserved token {{ PolyLookupSearch }}.

For example, I want to search for Categories that have name contains "what-i'm-searching" or description contains "what-i'm-searching", my view filter should look like this

![image](https://user-images.githubusercontent.com/8686497/229862661-c580f59d-337d-41a7-92fc-e6972cf87f10.png)

You don’t need to do this in the latest release, as it will check the view and insert the search token for you automatically.

**Comment by kevinhuizer** [comment]
Awesome, I will update to the latest version and report it back to you!
