### ISSUE TITLE
Documentation not clear for otb N:N

### ISSUE THREAD

**Issue by easybeat** [khoait/DCE.PCF#79]
Hi

I found the documentation and wording for otb N:N not clear. The help on "Relationsship Name" and "Relationship2 Name" should be updated.

<img width="292" alt="image" src="https://github.com/khoait/DCE.PCF/assets/37217887/272a135b-19b2-4835-893c-2072d9123021">

It should not say "relationship schema name". As I did understand that you meant the "relationsship table name".

It should say "relationship name" and maybe add my screen shot.

Does that make sense?

Kind regards
Beat

**Comment by khoait** [comment]
@easybeat thanks for your feedback! I think it's more about documentation than a bug. 

In the classic UI it is Relationship Schema Name

<img width="387" alt="relationship schema name" src="https://github.com/khoait/DCE.PCF/assets/8686497/d5ae6d4b-90b0-4fb2-b19a-26b2abe8f524">

I'll update the wiki page to be clearer with screenshots.

**Comment by khoait** [comment]
updated relationship name prop description in Wiki.

Please let me know if any suggestions / issues / control ideas. And consider giving the repo a star if it helps 😊
