### ISSUE TITLE
Multiselect Dropdown(Poly) remains at 'Loading'

### ISSUE THREAD

**Issue by mkardekar** [khoait/DCE.PCF#87]
Hi,

Control remains at ‘Loading’

1)	I’ve MAActivities entity form
2)	I’ve Community Dev Plan(second entity) as a single lookup in the form
3)	I want to have multiple select Focus Area(third entity) lookup to single select lookup of CDP(second entity).

However not sure about configuration or is it a bug? Can you correct me pls? Need to show it on Monday, will benefit you as well in terms of sponsorship.

Thanks
Nik

Ps: Refer attachments.
[Doc2.docx](https://github.com/khoait/DCE.PCF/files/13623149/Doc2.docx)
![Capture1](https://github.com/khoait/DCE.PCF/assets/78626869/cb23f1a8-f2ed-4cc9-b5ce-3fd666009c90)

**Comment by khoait** [comment]
Hi @mkardekar thanks for your feedback.

I think it's just a misconfiguration. Let me know if I understand it correctly.

On the MAActivity form, you want to lookup to a CDP, and based on the select CDP you want to select multiple Areas?

**Comment by khoait** [comment]
@mkardekar I'm closing this for now. please try the latest release and feel free to open new issue if it doesn't work for you. thanks!
