### ISSUE TITLE
Multiselect Lookup not visible on inactive record form

### ISSUE THREAD

**Issue by maerger** [khoait/DCE.PCF#88]
**Component**

DCE PCF Components 1.0.3.1

**Describe the bug**

On an inactive record the selected n:n items are not visible on the form

**Steps to Reproduce**

1. Open an active record form with the PolyLookup v1.1.4 component
2. Add some n:n records
3. Save
4. Deactivate the record
5. Hit Refresh
6. The selected records are not shown anymore

**Expected behavior**

View of the selected records in readonly mode

**Actual behavior**

selected n:n Records are not visible

**Screenshots**

![image](https://github.com/khoait/DCE.PCF/assets/6177363/cd0d89ed-ac77-486e-8889-cc9a9854db96)

![image](https://github.com/khoait/DCE.PCF/assets/6177363/42d62f3d-6449-481c-ace6-ddbb4231251f)

After deactivate:
![image](https://github.com/khoait/DCE.PCF/assets/6177363/8f4814e9-5048-4748-8d3f-b995e4a956f6)

After refresh:
![image](https://github.com/khoait/DCE.PCF/assets/6177363/d3c8f23c-3b55-4ffc-8612-abbfe8c1ba8f)

**Comment by khoait** [comment]
@maerger thanks for reporting! I'll look into this.

**Comment by khoait** [comment]
@maerger should be fixed in [Release v1.0.4.1](https://github.com/khoait/DCE.PCF/releases/tag/v1.0.4.1)
