### ISSUE TITLE
Multi Language User Interface Support

### ISSUE THREAD

**Issue by maerger** [khoait/DCE.PCF#95]
**Describe Problem**

We use the control in a German environment. It would be nice to have German translations for the controls end user interface

**Suggest Solution/Expectation**

Add the ability to configure wording of end user interface or translation at runtime (language resources)

**Comment by maerger** [comment]
I tried to contribute and solve this but did not manage to build the solution using msbuild. I'm quite new in react and PCF - maybe you have some rough description on how to init and build (I'm using vissual studio code or 2022)...

**Comment by khoait** [comment]
Thanks for your interest in the repo and glad to hear that the control is helpful! This will help to motivate me to put more effort in terms of features and variety of controls.

I'll look into language feature using supported web resources. Also review the build process with proper documentation.

I'm trying to make some time this. I'll let you know when it's available.

**Comment by khoait** [comment]
hi @maerger. I added language support by passing a URL to a .resx web resource to the new `Language Pack Path` property. Please try it in the new release here https://github.com/khoait/DCE.PCF/releases/tag/v1.0.5.0

Let me know what you think and feel free to open new issues if you find something odd.

I also update the readme with the build steps. Hope it helps when you want to contribute.

Cheers!

**Comment by maerger** [comment]
Hi @khoait I installed the new version in our dev environment and uploaded a german webresource like this:
![image](https://github.com/khoait/DCE.PCF/assets/6177363/4dd7418c-c060-486d-b5f9-fd1f4a27bd43)

And put the path to my form:
![image](https://github.com/khoait/DCE.PCF/assets/6177363/69e48eda-3269-46be-8e5b-eca03a7b7888)

Seems that everything is working fine so far - thanks! 

How would it be if we have an organization supporting multiple languages? I think language switch is supported by default on components if the webresources with the correct language code are provided.

**Comment by khoait** [comment]
@maerger we'll need to include language packs in the component for default multi languages support. It'll affect the size of the component, I'm not sure if we should unless there is a high demand for this. 
However, I have made it ready for if we want, we just include an additional language pack in the component and build.
Let me know what you think.
