### ISSUE TITLE
No dropdown items visible in  PolyLookup using OOTB N:N relation

### ISSUE THREAD

**Issue by N1x0** [khoait/DCE.PCF#99]
**Component**
Release V1.0.5.0
PolyLookup v1.3.0

**Describe the bug**

No items are visible in the dropdown menu when using the standard N:N relationship between a custom object and the standard Account object. The component does not produce any errors and it looks like it does try to load records, however even when inspecting them using the elementsviewer entries remain blank

![image](https://github.com/khoait/DCE.PCF/assets/47623143/980253f8-bdf8-4aca-8d3f-c6d6a0eaaec8)

**Steps to Reproduce**

* Add PolyLookup to custom Object "contracts"
* Set bound field to single line text custom text field "Account Lookups
* Set relationship to "nton"
* Set relationship name  "Contracts_Account_Account" (not table name as highlighted the wiki
* Relationship 2 Name remains blank as it is not a custom N:N
* Tested both with output to selected field and withou
* Tested both with and without lookup view
* Item Limit: 50
* No language pack path
* Show on all devices

![image](https://github.com/khoait/DCE.PCF/assets/47623143/89e388da-6080-4ad7-b8f8-75d28a0f7aa7)

**Additional context**
Tested both in classic and unified UI, **on Web only**
Type: Production
Dataverse Version:  9.2.24022.00196
Security Roles: System Administrator, System Customizer

**Comment by khoait** [comment]
thanks for reporting. I'll look into this. In the mean time, you can try the previous version to see if it works for you.

**Comment by MB-Motive** [comment]
@N1x0 

Just a thought, are you missing the publisher prefix on the Relationship Name static value?

"Contracts_Account_Account" should be "publisherPrefix_Contracts_Account_Account"

**Comment by N1x0** [comment]
@MB-Motive  That was it! Thanks a lot for pointing this out, it wasn't obvious to me that the publisher prefix was needed from the docs. Will add a PR to explicitly state this for others like myself who are rather new to dataverse.
